spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${LAB_DB_URL}
    username: ${LAB_DB_USER}
    password: ${LAB_DB_PASSWORD}
  thymeleaf:
    cache: true

server:
  forward-headers-strategy: framework
