-- MySQL 9.4, InnoDB, utf8mb4
SET NAMES utf8mb4;

CREATE TABLE VaiTro (
  MaVaiTro VARCHAR(10) PRIMARY KEY,
  TenVaiTro VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE NguoiDung (
  MaNguoiDung VARCHAR(50) PRIMARY KEY,
  HoTen VARCHAR(150) NOT NULL,
  Email VARCHAR(254) NOT NULL,
  MatKhau VARCHAR(100) NOT NULL,
  LopDonVi VARCHAR(150),
  MaVaiTro VARCHAR(10) NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'CHO_DUYET',
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT UK_NguoiDung_Email UNIQUE (Email),
  CONSTRAINT FK_NguoiDung_VaiTro FOREIGN KEY (MaVaiTro) REFERENCES VaiTro(MaVaiTro),
  CONSTRAINT CK_NguoiDung_TrangThai CHECK (TrangThai IN ('CHO_DUYET','HOAT_DONG','BI_KHOA'))
) ENGINE=InnoDB;

CREATE TABLE NhomPhong (
  MaNhom VARCHAR(50) PRIMARY KEY,
  TenNhom VARCHAR(150) NOT NULL UNIQUE,
  MoTa TEXT
) ENGINE=InnoDB;

CREATE TABLE Phong (
  MaPhong VARCHAR(50) PRIMARY KEY,
  TenPhong VARCHAR(150) NOT NULL,
  MaNhom VARCHAR(50) NOT NULL,
  ViTri VARCHAR(255) NOT NULL,
  SucChua INT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'SAN_SANG',
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT FK_Phong_NhomPhong FOREIGN KEY (MaNhom) REFERENCES NhomPhong(MaNhom),
  CONSTRAINT CK_Phong_SucChua CHECK (SucChua > 0),
  CONSTRAINT CK_Phong_TrangThai CHECK (TrangThai IN ('SAN_SANG','BAO_TRI','NGUNG_SU_DUNG'))
) ENGINE=InnoDB;

CREATE TABLE LoaiThietBi (
  MaLoai VARCHAR(50) PRIMARY KEY,
  TenLoai VARCHAR(150) NOT NULL UNIQUE,
  YeuCauGVHuongDan BOOLEAN NOT NULL DEFAULT FALSE,
  LaThietBiDiDong BOOLEAN NOT NULL DEFAULT FALSE,
  MoTa TEXT
) ENGINE=InnoDB;

CREATE TABLE ThietBi (
  MaThietBi VARCHAR(50) PRIMARY KEY,
  TenThietBi VARCHAR(150) NOT NULL,
  MaLoai VARCHAR(50) NOT NULL,
  SoSerial VARCHAR(100),
  Model VARCHAR(100),
  MaPhong VARCHAR(50),
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'SAN_SANG',
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT UK_ThietBi_Serial UNIQUE (SoSerial),
  CONSTRAINT FK_ThietBi_Loai FOREIGN KEY (MaLoai) REFERENCES LoaiThietBi(MaLoai),
  CONSTRAINT FK_ThietBi_Phong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
  CONSTRAINT CK_ThietBi_TrangThai CHECK (TrangThai IN ('SAN_SANG','DANG_SU_DUNG','HONG','BAO_TRI','NGUNG_SU_DUNG'))
) ENGINE=InnoDB;

CREATE TABLE TaiNguyen (
  MaTaiNguyen VARCHAR(50) PRIMARY KEY,
  LoaiTaiNguyen VARCHAR(20) NOT NULL,
  MaPhong VARCHAR(50),
  MaThietBi VARCHAR(50),
  PhongUnique VARCHAR(50) GENERATED ALWAYS AS (CASE WHEN LoaiTaiNguyen='PHONG' THEN MaPhong ELSE NULL END) STORED,
  ThietBiUnique VARCHAR(50) GENERATED ALWAYS AS (CASE WHEN LoaiTaiNguyen='THIET_BI' THEN MaThietBi ELSE NULL END) STORED,
  CONSTRAINT UK_TaiNguyen_Phong UNIQUE (PhongUnique),
  CONSTRAINT UK_TaiNguyen_ThietBi UNIQUE (ThietBiUnique),
  CONSTRAINT FK_TaiNguyen_Phong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
  CONSTRAINT FK_TaiNguyen_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi),
  CONSTRAINT CK_TaiNguyen_Loai CHECK (
    (LoaiTaiNguyen='PHONG' AND MaPhong IS NOT NULL AND MaThietBi IS NULL) OR
    (LoaiTaiNguyen='THIET_BI' AND MaPhong IS NULL AND MaThietBi IS NOT NULL)
  )
) ENGINE=InnoDB;

CREATE TABLE TietHoc (
  MaTiet INT PRIMARY KEY,
  TenTiet VARCHAR(50) NOT NULL UNIQUE,
  GioBatDau TIME NOT NULL,
  GioKetThuc TIME NOT NULL,
  CONSTRAINT CK_TietHoc_Gio CHECK (GioKetThuc > GioBatDau)
) ENGINE=InnoDB;

CREATE TABLE PhieuDangKy (
  MaPhieu VARCHAR(50) PRIMARY KEY,
  MaNguoiTao VARCHAR(50) NOT NULL,
  MaPhong VARCHAR(50) NOT NULL,
  LoaiPhieu VARCHAR(20) NOT NULL,
  MucDich TEXT NOT NULL,
  SoNguoi INT NOT NULL,
  NgayBatDau DATE NOT NULL,
  NgayKetThuc DATE NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'CHO_DUYET',
  NgayTao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  NgayCapNhat DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT FK_Phieu_NguoiTao FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT FK_Phieu_Phong FOREIGN KEY (MaPhong) REFERENCES Phong(MaPhong),
  CONSTRAINT CK_Phieu_Loai CHECK (LoaiPhieu IN ('GIANG_DAY','HOC_TAP','NGHIEN_CUU')),
  CONSTRAINT CK_Phieu_SoNguoi CHECK (SoNguoi > 0),
  CONSTRAINT CK_Phieu_Ngay CHECK (NgayKetThuc >= NgayBatDau),
  CONSTRAINT CK_Phieu_TrangThai CHECK (TrangThai IN ('CHO_DUYET','DA_DUYET','TU_CHOI','DA_HUY','DANG_SU_DUNG','HOAN_THANH'))
) ENGINE=InnoDB;

CREATE TABLE PhieuGiangDay (
  MaPhieu VARCHAR(50) PRIMARY KEY,
  MaHocPhan VARCHAR(50) NOT NULL,
  TenLopNhom VARCHAR(100) NOT NULL,
  CONSTRAINT FK_PhieuGiangDay_Phieu FOREIGN KEY (MaPhieu) REFERENCES PhieuDangKy(MaPhieu) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE PhieuHuongDan (
  MaPhieu VARCHAR(50) PRIMARY KEY,
  MaGVHuongDan VARCHAR(50) NOT NULL,
  CONSTRAINT FK_PhieuHuongDan_Phieu FOREIGN KEY (MaPhieu) REFERENCES PhieuDangKy(MaPhieu) ON DELETE CASCADE,
  CONSTRAINT FK_PhieuHuongDan_GV FOREIGN KEY (MaGVHuongDan) REFERENCES NguoiDung(MaNguoiDung)
) ENGINE=InnoDB;

CREATE TABLE LichDangKy (
  MaLich BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaPhieu VARCHAR(50) NOT NULL,
  Thu TINYINT NOT NULL,
  MaTiet INT NOT NULL,
  CONSTRAINT UK_LichDangKy UNIQUE (MaPhieu, Thu, MaTiet),
  CONSTRAINT FK_Lich_Phieu FOREIGN KEY (MaPhieu) REFERENCES PhieuDangKy(MaPhieu) ON DELETE CASCADE,
  CONSTRAINT FK_Lich_Tiet FOREIGN KEY (MaTiet) REFERENCES TietHoc(MaTiet),
  CONSTRAINT CK_Lich_Thu CHECK (Thu BETWEEN 2 AND 8)
) ENGINE=InnoDB;

CREATE TABLE PhieuDangKyThietBi (
  MaPhieu VARCHAR(50) NOT NULL,
  MaThietBi VARCHAR(50) NOT NULL,
  DaPhanBo BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (MaPhieu, MaThietBi),
  CONSTRAINT FK_PDKTB_Phieu FOREIGN KEY (MaPhieu) REFERENCES PhieuDangKy(MaPhieu) ON DELETE CASCADE,
  CONSTRAINT FK_PDKTB_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE XuLyPhieu (
  MaXuLy BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaPhieu VARCHAR(50) NOT NULL,
  MaNguoiXuLy VARCHAR(50) NOT NULL,
  HanhDong VARCHAR(20) NOT NULL,
  LyDo TEXT,
  ThoiDiem DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT FK_XuLy_Phieu FOREIGN KEY (MaPhieu) REFERENCES PhieuDangKy(MaPhieu),
  CONSTRAINT FK_XuLy_Nguoi FOREIGN KEY (MaNguoiXuLy) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_XuLy_HanhDong CHECK (HanhDong IN ('PHE_DUYET','TU_CHOI','HUY')),
  CONSTRAINT CK_XuLy_LyDo CHECK (HanhDong='PHE_DUYET' OR LyDo IS NOT NULL)
) ENGINE=InnoDB;

CREATE TABLE LichChan (
  MaLichChan BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaTaiNguyen VARCHAR(50) NOT NULL,
  NgayBatDau DATE NOT NULL,
  NgayKetThuc DATE NOT NULL,
  Thu TINYINT,
  MaTiet INT,
  LyDo TEXT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'HIEU_LUC',
  MaNguoiTao VARCHAR(50) NOT NULL,
  CONSTRAINT FK_LichChan_TaiNguyen FOREIGN KEY (MaTaiNguyen) REFERENCES TaiNguyen(MaTaiNguyen),
  CONSTRAINT FK_LichChan_Tiet FOREIGN KEY (MaTiet) REFERENCES TietHoc(MaTiet),
  CONSTRAINT FK_LichChan_Nguoi FOREIGN KEY (MaNguoiTao) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_LichChan_Ngay CHECK (NgayKetThuc >= NgayBatDau),
  CONSTRAINT CK_LichChan_Thu CHECK (Thu IS NULL OR Thu BETWEEN 2 AND 8),
  CONSTRAINT CK_LichChan_TrangThai CHECK (TrangThai IN ('HIEU_LUC','DA_HUY'))
) ENGINE=InnoDB;

CREATE TABLE PhienSuDung (
  MaPhien BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaLich BIGINT NOT NULL,
  NgaySuDung DATE NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'CHUA_BAT_DAU',
  ThoiDiemCheckIn DATETIME(6),
  ThoiDiemCheckOut DATETIME(6),
  MaNguoiCheckIn VARCHAR(50),
  MaNguoiCheckOut VARCHAR(50),
  CONSTRAINT UK_Phien_LichNgay UNIQUE (MaLich, NgaySuDung),
  CONSTRAINT FK_Phien_Lich FOREIGN KEY (MaLich) REFERENCES LichDangKy(MaLich),
  CONSTRAINT FK_Phien_CheckIn FOREIGN KEY (MaNguoiCheckIn) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT FK_Phien_CheckOut FOREIGN KEY (MaNguoiCheckOut) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_Phien_TrangThai CHECK (TrangThai IN ('CHUA_BAT_DAU','DANG_SU_DUNG','HOAN_THANH','VANG_MAT')),
  CONSTRAINT CK_Phien_ThoiGian CHECK (ThoiDiemCheckOut IS NULL OR ThoiDiemCheckIn IS NULL OR ThoiDiemCheckOut >= ThoiDiemCheckIn)
) ENGINE=InnoDB;

CREATE TABLE PhienSuDungThietBi (
  MaPhien BIGINT NOT NULL,
  MaThietBi VARCHAR(50) NOT NULL,
  TinhTrangNhan VARCHAR(255) NOT NULL,
  TinhTrangTra VARCHAR(255),
  GhiChu TEXT,
  PRIMARY KEY (MaPhien, MaThietBi),
  CONSTRAINT FK_PSDTB_Phien FOREIGN KEY (MaPhien) REFERENCES PhienSuDung(MaPhien) ON DELETE CASCADE,
  CONSTRAINT FK_PSDTB_ThietBi FOREIGN KEY (MaThietBi) REFERENCES ThietBi(MaThietBi)
) ENGINE=InnoDB;

CREATE TABLE SuCo (
  MaSuCo VARCHAR(50) PRIMARY KEY,
  MaTaiNguyen VARCHAR(50) NOT NULL,
  MaPhien BIGINT,
  MaNguoiBao VARCHAR(50) NOT NULL,
  MaNguoiXuLy VARCHAR(50),
  MucDo VARCHAR(20) NOT NULL,
  MoTa TEXT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'MOI',
  ThoiDiemBao DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  ThoiDiemHoanThanh DATETIME(6),
  KetQua TEXT,
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT FK_SuCo_TaiNguyen FOREIGN KEY (MaTaiNguyen) REFERENCES TaiNguyen(MaTaiNguyen),
  CONSTRAINT FK_SuCo_Phien FOREIGN KEY (MaPhien) REFERENCES PhienSuDung(MaPhien),
  CONSTRAINT FK_SuCo_NguoiBao FOREIGN KEY (MaNguoiBao) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT FK_SuCo_NguoiXuLy FOREIGN KEY (MaNguoiXuLy) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_SuCo_MucDo CHECK (MucDo IN ('THAP','TRUNG_BINH','CAO','NGHIEM_TRONG')),
  CONSTRAINT CK_SuCo_TrangThai CHECK (TrangThai IN ('MOI','DANG_XU_LY','DA_XU_LY','DA_HUY')),
  CONSTRAINT CK_SuCo_ThoiGian CHECK (ThoiDiemHoanThanh IS NULL OR ThoiDiemHoanThanh >= ThoiDiemBao)
) ENGINE=InnoDB;

CREATE TABLE BaoTri (
  MaBaoTri VARCHAR(50) PRIMARY KEY,
  MaTaiNguyen VARCHAR(50) NOT NULL,
  MaNguoiPhuTrach VARCHAR(50) NOT NULL,
  NgayBatDau DATETIME(6) NOT NULL,
  NgayKetThuc DATETIME(6),
  NoiDung TEXT NOT NULL,
  TrangThai VARCHAR(20) NOT NULL DEFAULT 'CHO_XU_LY',
  KetQua TEXT,
  VersionNo BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT FK_BaoTri_TaiNguyen FOREIGN KEY (MaTaiNguyen) REFERENCES TaiNguyen(MaTaiNguyen),
  CONSTRAINT FK_BaoTri_Nguoi FOREIGN KEY (MaNguoiPhuTrach) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_BaoTri_TrangThai CHECK (TrangThai IN ('CHO_XU_LY','DANG_BAO_TRI','HOAN_THANH','DA_HUY')),
  CONSTRAINT CK_BaoTri_Ngay CHECK (NgayKetThuc IS NULL OR NgayKetThuc >= NgayBatDau),
  CONSTRAINT CK_BaoTri_HoanThanh CHECK (TrangThai <> 'HOAN_THANH' OR (NgayKetThuc IS NOT NULL AND KetQua IS NOT NULL))
) ENGINE=InnoDB;

CREATE TABLE BaoTriSuCo (
  MaBaoTri VARCHAR(50) NOT NULL,
  MaSuCo VARCHAR(50) NOT NULL,
  PRIMARY KEY (MaBaoTri, MaSuCo),
  CONSTRAINT UK_BaoTriSuCo_SuCo UNIQUE (MaSuCo),
  CONSTRAINT FK_BTSC_BaoTri FOREIGN KEY (MaBaoTri) REFERENCES BaoTri(MaBaoTri) ON DELETE CASCADE,
  CONSTRAINT FK_BTSC_SuCo FOREIGN KEY (MaSuCo) REFERENCES SuCo(MaSuCo)
) ENGINE=InnoDB;

CREATE TABLE TienDoBaoTri (
  MaTienDo BIGINT AUTO_INCREMENT PRIMARY KEY,
  MaBaoTri VARCHAR(50) NOT NULL,
  ThoiDiem DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  TrangThai VARCHAR(20) NOT NULL,
  NoiDung TEXT NOT NULL,
  MaNguoiCapNhat VARCHAR(50) NOT NULL,
  CONSTRAINT FK_TienDo_BaoTri FOREIGN KEY (MaBaoTri) REFERENCES BaoTri(MaBaoTri) ON DELETE CASCADE,
  CONSTRAINT FK_TienDo_Nguoi FOREIGN KEY (MaNguoiCapNhat) REFERENCES NguoiDung(MaNguoiDung),
  CONSTRAINT CK_TienDo_TrangThai CHECK (TrangThai IN ('CHO_XU_LY','DANG_BAO_TRI','HOAN_THANH','DA_HUY'))
) ENGINE=InnoDB;
